# Generated by Django 5.2.17 on 2026-08-10 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('lob', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('method_of_ordering', models.CharField(blank=True, max_length=255)),
                ('account_status', models.CharField(blank=True, max_length=128)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('f25_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='retention.site')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='RepAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_initials', models.CharField(max_length=16)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rep_assignment', to='retention.site')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_initials', models.CharField(blank=True, max_length=16)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('q1_last_order_feedback', models.TextField(blank=True)),
                ('q2_working_well', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('q4_could_improve', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('actions_required', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='retention.site')),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
    ]
