# Generated by Django 5.2.17 on 2026-08-10 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='corrections_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='data_corrections',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('raw_status', models.CharField(max_length=128)),
                ('observed_date', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='retention.site')),
            ],
            options={
                'ordering': ['-observed_date'],
            },
        ),
    ]
