# Generated by Django 5.2.17 on 2026-08-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0002_callrecord_corrections_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='raw_account_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
