# Generated by Django 5.2.17 on 2026-08-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0003_site_raw_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='has_native_id',
            field=models.BooleanField(default=True),
        ),
    ]
