# Generated by Django 5.2.17 on 2026-08-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0004_site_has_native_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='source',
            field=models.CharField(choices=[('import', 'Imported from tracker'), ('app', 'Logged in app')], default='import', max_length=16),
        ),
    ]
