# Generated by Django 5.2.17 on 2026-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0005_callrecord_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(blank=True, max_length=512)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('sites_created', models.IntegerField(default=0)),
                ('sites_updated', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('no_assets', 'No assets/route dormant'), ('completed_survey', 'Completed survey'), ('invalid_contact', 'Missing/invalid contact details'), ('follow_up', 'Follow up/Issue (Seed ticket or email the branch)'), ('awaiting_email', 'Awaiting email response'), ('french_account', 'French accounts'), ('left_vm', 'Left VM/call back'), ('temp_closed', 'Temp closed due to season')], default='', max_length=32),
        ),
    ]
