# Generated by Django 5.2.17 on 2026-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0006_importlog_site_call_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('text', 'Text message'), ('in_person', 'In person')], default='', max_length=32),
        ),
    ]
